<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Daily Sales Report - {{ $date }}</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Play:wght@400;700&display=swap');
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: "Play", sans-serif;font-weight: 400;
        font-style: normal; font-size: 13px; padding: 20px; }
        
        .header { margin-bottom: 20px; padding-bottom: 15px; border-bottom: 2px solid #333; }
        .header h1 {text-align: center; font-size: 20px; margin: 20px 0;color : #1d3557;text-transform: uppercase; }
        .header p { font-size: 12px; color: #666; }
        
        .info-section { margin-bottom: 20px; }
        .info-row { display: flex; justify-content: space-between; margin-bottom: 5px; }
        .info-label { font-weight: bold; color: #333; }
        .info-value { color: #666; }
        
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background-color: #f0f0f0; padding: 10px; text-align: left; border: 1px solid #ddd; font-weight: bold; }
        td { padding: 10px; border: 1px solid #ddd; }
        
        .summary-box { background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .summary-row { display: flex; justify-content: space-between; margin-bottom: 8px; }
        .summary-label { font-weight: bold; }
        .summary-value { font-size: 13px; }
        
        .total-row { border-top: 2px solid #333; padding-top: 10px; margin-top: 10px; }
        .total-value { font-size: 16px; font-weight: bold; color: #c1121f; }
        
        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    {{-- HEADER --}}
    <div class="header">
        <h1>Daily Sales Report</h1>
        <p>Company name: <span style="text-transform: uppercase;font-weight: bold;">{{ $company_name }}</span></p>
        <p>Branch: {{ $branch_name }}</p>
        <p>Date: {{ $date }}</p>
    </div>

    {{-- REPORT INFO --}}
    <div class="info-section">
        <div class="info-row">
            <span class="info-label">Report ID:</span>
            <span class="info-value">{{ $report_id }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Report Date:</span>
            <span class="info-value">{{ $date }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Branch:</span>
            <span class="info-value">{{ $branch_name }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Generated At:</span>
            <span class="info-value">{{ $report->generated_at->format('d M Y H:i:s A') }}</span>
        </div>
    </div>

    {{-- SUMMARY METRICS --}}
    <div class="summary-box">
        <h3 style="margin-bottom: 15px;">Sales Summary</h3>
        
        <div class="summary-row">
            <span class="summary-label">Total Sales:</span>
            <span class="summary-value">${{ number_format($report->total_sales, 2) }}</span>
        </div>
        
        <div class="summary-row">
            <span class="summary-label">Total Transactions:</span>
            <span class="summary-value">{{ number_format($report->transaction_count) }}</span>
        </div>
        
        <div class="summary-row">
            <span class="summary-label">Average Transaction:</span>
            <span class="summary-value">${{ number_format($report->average_transaction, 2) }}</span>
        </div>
        
        <div class="summary-row">
            <span class="summary-label">Total Tax:</span>
            <span class="summary-value">${{ number_format($report->total_tax, 2) }}</span>
        </div>
        
        <div class="summary-row">
            <span class="summary-label">Total Discount:</span>
            <span class="summary-value">${{ number_format($report->total_discount, 2) }}</span>
        </div>
        
        <div class="summary-row">
            <span class="summary-label">Total Customers:</span>
            <span class="summary-value">{{ number_format($report->customer_count) }}</span>
        </div>

        <div class="summary-row">
            <span class="summary-label">Gross Profit:</span>
            <span class="summary-value" style="color:#40916c;">${{ number_format($report->gross_profit, 2) }}</span>
        </div>
        
        <div class="summary-row total-row">
            <span class="summary-label">Net Sales:</span>
            <span class="total-value">${{ number_format($report->net_sales, 2) }}</span>
        </div>
    </div>

    {{-- FOOTER --}}
    <div class="footer">
        <p>Generated by POS System on {{ now()->format('d M Y H:i:s A') }}</p>
        <p>{{ $company_name }}</p>
    </div>
</body>
</html>